djangotest2/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('account_info/', views.AccountInfoView.as_view(), name="account_info"),

    path('fruit/',views.FruitList.as_view(),name='fruit_index'),
    path('fruit/create/',views.FruitCreateView.as_view(),name='fruit_create'),

    path('test/',views.Test.as_view(),name="test"),

]

djangotest2/djangotest2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")) # accounts.urls.pyを読み込むための設定を追加
]

djangotest2/accounts/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager,
                                        AbstractBaseUser,
                                        PermissionsMixin)
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def _create_user(self, email, account_id, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, account_id=account_id, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, account_id, password=None, **extra_fields):
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(
            email=email,
            account_id=account_id,
            password=password,
            **extra_fields,
        )

    def create_superuser(self, email, account_id, password, **extra_fields):
        extra_fields['is_active'] = True
        extra_fields['is_staff'] = True
        extra_fields['is_superuser'] = True
        return self._create_user(
            email=email,
            account_id=account_id,
            password=password,
            **extra_fields,
        )


class User(AbstractBaseUser, PermissionsMixin):

    account_id = models.CharField(
        verbose_name=_("account_id"),
        unique=True,
        max_length=10
    )
    email = models.EmailField(
        verbose_name=_("email"),
        unique=True
    )
    first_name = models.CharField(
        verbose_name=_("first_name"),
        max_length=150,
        null=True,
        blank=False
    )
    last_name = models.CharField(
        verbose_name=_("last_name"),
        max_length=150,
        null=True,
        blank=False
    )
    birth_date = models.DateField(
        verbose_name=_("birth_date"),
        blank=True,
        null=True
    )
    is_superuser = models.BooleanField(
        verbose_name=_("is_superuer"),
        default=False
    )
    is_staff = models.BooleanField(
        verbose_name=_('staff status'),
        default=False,
    )
    is_active = models.BooleanField(
        verbose_name=_('active'),
        default=True,
    )
    created_at = models.DateTimeField(
        verbose_name=_("created_at"),
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name=_("updateded_at"),
        auto_now=True
    )

    objects = UserManager()

    USERNAME_FIELD = 'account_id' # ログイン時、ユーザー名の代わりにaccount_idを使用
    REQUIRED_FIELDS = ['email']  # スーパーユーザー作成時にemailも設定する

    def __str__(self):
        return self.account_id


class Fruit(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="名前"
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name="価格"
    )
    remarks = models.TextField(
        blank=True,
        verbose_name="詳細"
    )
    category = models.CharField(
        max_length=100,
        verbose_name="カテゴリ"
    )
    created_at = models.DateTimeField(
        verbose_name=_("作成日"),
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name=_("更新日"),
        auto_now=True
    )
    def __str__(self):
        return self.name

djangotest2/masta/models.py
from django.db import models

# Create your models here.
class FruitCategoryMasta(models.Model):
    category_name = models.CharField(max_length=100)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = 'フルーツカテゴリマスタ' # 複数系
        verbose_name_plural='フルーツカテゴリマスタ'    # 任意の複数系(管理画面で複数系にならないように指定)

djangotest2/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm

from .models import User,Fruit

from masta.models import FruitCategoryMasta

from django import forms

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "account_id",
            "email",
            "first_name",
            "last_name",
            "birth_date",
        )

# ログインフォームを追加
class LoginFrom(AuthenticationForm):
    class Meta:
        model = User


class RegistForm(forms.ModelForm):
    """ なぜかKEYが登録されてしまう。
    category = forms.ModelChoiceField(
        queryset=FruitCategoryMasta.objects.all(),
        label='カテゴリ',
        to_field_name='id',
    )
    """

    category = forms.ChoiceField(
        choices=[(d.id,d.category_name) for d in FruitCategoryMasta.objects.all()],
        label="カテゴリ"
    )

    class Meta:
        model = Fruit
        #fields = ['name', 'price', 'remarks','category']  # 作成フォームに表示するフィールド
        fields = '__all__'

djangotest2/accounts/views.py
from django.contrib.auth import login, authenticate
from django.views.generic import TemplateView, CreateView,ListView
from django.contrib.auth.views import LoginView as BaseLoginView,  LogoutView as BaseLogoutView
from django.urls import reverse_lazy
from .forms import SignUpForm, LoginFrom, RegistForm
from .models import User,Fruit
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings

class IndexView(TemplateView):
    print("IndexView")
    template_name = "index.html"


class SignupView(CreateView):
    print("SignupView")
    form_class = SignUpForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("accounts:index")

    def form_valid(self, form):
        # login after signup
        response = super().form_valid(form)
        account_id = form.cleaned_data.get("account_id")
        password = form.cleaned_data.get("password1")
        user = authenticate(account_id=account_id, password=password)
        login(self.request, user)
        return response


class LoginView(BaseLoginView):
    print("LoginView")
    form_class = LoginFrom
    template_name = "accounts/login.html"


class LogoutView(BaseLogoutView):
    print("LogoutView")
    success_url = reverse_lazy("accounts:index")


# クラスベースビュー
# LoginRequiredMixin は、ログインしているか判定
class AccountInfoView(LoginRequiredMixin,TemplateView):

    # どのテンプレートを使うか
    template_name="accounts/account_info.html"

    # ログインされていなければリダイレクトするURLを
    login_url = reverse_lazy(settings.LOGIN_URL)  # ログインページのURLを指定

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # ユーザーモデルをクエリしてユーザーオブジェクトを取得
        user = User.objects.filter(account_id=self.request.user.account_id)

        # ログ表示
        for u in user:
            print(u.account_id)
            print(u.email)
            print(u.first_name)
            print(u.last_name)
            print(u.birth_date)
            print(u.created_at)
            print(u.updated_at)

        # ユーザがいるかチェック
        if len(user) > 0:
            # 任意の変数を設定 ユーザがいる場合
            variable1 = 'ユーザ'
            variable2 = user[0].account_id
        else:
            # 任意の変数を設定　ユーザがいない場合
            variable1 = 'ユーザ'
            variable2 = 'がいません'

        # コンテキストに追加
        context['user'] = user
        context['variable1'] = variable1
        context['variable2'] = variable2


        return context



# フルーツ一覧を表示するクラスベースビュー
class FruitList(LoginRequiredMixin,ListView):
    model = Fruit
    template_name = "accounts/fruit_list.html"



class FruitCreateView(LoginRequiredMixin,CreateView):
    # 画面を表示するのに必要な情報↓
    model = Fruit
    '''
    form_classと併用はできない
    fields = ['name', 'price', 'remarks','category']  # 作成フォームに表示するフィールド
    '''
    template_name = "accounts/fruit_create.html"
    form_class = RegistForm

    # 登録処理をするのに必要な構文↓
    success_url = reverse_lazy('accounts:fruit_index')  # 登録後のリダイレクト先
    def form_valid(self, form):
        # フォームのデータを保存する前に何か特別な処理を追加する場合はここに記述
        return super().form_valid(form)


class Test(TemplateView):
    template_name = "vueindex.html"

djangotest2/accounts/templates/accounts/account_info.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>アカウント情報</title>
</head>

<body>
    <!--
    {{variable_name}}

    {#comment#}

    {%for i in num%}
    {%endfor%}

    {%if true_or_false%}
    {%endif%}

-->
    <h1>{{variable1}}：{{variable2}}の情報</h1>
    {%for u in user%}
    <p>account_id : {{u.account_id}}</p>
    <p>email : {{u.email}}</p>
    <p>first_name : {{u.first_name}}</p>
    <p>last_name : {{u.last_name}}</p>
    <p>birth_date : {{u.birth_date}}</p>
    <p>created_at : {{u.created_at}}</p>
    <p>updated_at : {{u.updated_at}}</p>
    {%endfor%}



</body>

</html>

djangotest2/accounts/templates/accounts/fruit_create.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>Create Fruit</title>
</head>

<body>
    <h1>Create Fruit</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>

    <hr>

    {# テンプレートエンジンとして読み込まないようにしてくれる書き方 verbatim #}
    {% verbatim %}
    <p>{{ form.as_p }}この書き方でなぜか上記必要項目が生成される</p>
    <p>登録処理はこのフォームを渡してきたクラスの def form_valid(): メソッドで実行される</p>
    {% endverbatim %}
</body>


</html>

djangotest2/accounts/templates/accounts/fruit_list.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FruitList</title>
</head>

<body>
    <div>
        <a href="{% url 'accounts:fruit_create' %}">regist</a>
        <p>href="{% url 'accounts:fruit_create' %}" 名前からパスを解決してくれる書き方</p>
    </div>
    <hr>
    <table>
        <tr>
            <th>name</th>
            <th>price</th>
            <th>remarks</th>
            <th>category</th>
            <th>created_at</th>
            <th>updated_at</th>
        </tr>
        {%for f in object_list%}
        <tr>
            <td>{{f.name}}</td>
            <td>{{f.price}}</td>
            <td>{{f.remarks}}</td>
            <td>{{f.category}}</td>
            <td>{{f.created_at}}</td>
            <td>{{f.updated_at}}</td>
        </tr>
        {%endfor%}
    </table>
    <p>object_listという名前で取得可能（modelに指定したモデル）</p>
</body>

</html>

djangotest2/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
<div class="h1">Login</div>
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    {{ field.label }}
    {{ field }}
    {{ field.errors }}
    <br>
    {% endfor %}
    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Login</button>
        <a href="{% url 'accounts:index' %}" class="btn btn-secondary">Back</a>
    </div>
</form>
{% endblock %}

djangotest2/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}
<div class="h1">Create account</div>
{% endblock %}

{% block content %}
<div>
    <br>
    <form method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
        {{ field.label }}
        {{ field }}
        {{ field.errors }}
        <br>
        {% endfor %}
        <div class="mt-3">
            <button type="submit" class="btn btn-primary">Create</button>
            <a href="{% url 'accounts:index' %}" class="btn btn-secondary">Back</a>
        </div>
    </form>
</div>
{% endblock %}

djangotest2/accounts/templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap5のCDNを設定 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <title>Account</title>
</head>

<body>
    <div class="container mx-auto text-center">
        {% block title %}
        {% endblock %}
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

djangotest2/accounts/templates/index.html
{% extends 'base.html' %}

{% block title %}
{% if user.is_authenticated %}
<div class="h1">MyPage</div>
{% else %}
<div class="h1">Main</div>
{% endif %}
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="h2">Welcome {{ user.first_name }} {{ user.last_name }}</div>
<div>
    <a href="/account_info">/account_info</a>
</div>
<div>
    <a href="/fruit">/fruit</a>
</div>

<a href="{% url 'accounts:logout' %}" class="btn btn-primary">Logout</a>
{% else %}
<a href="{% url 'accounts:signup' %}" class="btn btn-primary">Signup</a>
<a href="{% url 'accounts:login' %}" class="btn btn-primary">Login</a>
{% endif %}
{% endblock %}

djangotest2/templates/vueindex.html
<!doctype html><html lang=""><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="/favicon.ico"><title>testvue</title><script defer="defer" src="/static/js/chunk-vendors.feab805f.js"></script><script defer="defer" src="/static/js/app.9c31f6e6.js"></script><link href="/static/css/app.16b1c3fc.css" rel="stylesheet"></head><body><noscript><strong>We're sorry but testvue doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div></body></html>